---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
    #annotations:
    #alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    run: my-nginx
spec:
  #type: NodePort
  selector:
    run: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
