---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: gst-tgb-pub-dev-eks-blue
  labels:
    ingress.k8s.aws/stack: eks-test-group
spec:
  targetType: ip
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: sg-06870a088ca75aed4
      ports:
      - port: 80
  serviceRef:
    name: rollout-bluegreen-active
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:623397710446:targetgroup/TG-ALB-PRIV-DEV-EKS-BLUE/4ff4e8824d149531
---
apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: gst-tgb-pub-dev-eks-green
  labels:
    ingress.k8s.aws/stack: eks-test-group
spec:
  targetType: ip
  networking:
    ingress:
    - from:
      - securityGroup:
          groupID: sg-06870a088ca75aed4
      ports:
      - port: 80
  serviceRef:
    name: rollout-bluegreen-preview
    port: 80
  targetGroupARN: arn:aws:elasticloadbalancing:ap-northeast-2:623397710446:targetgroup/TG-ALB-PRIV-DEV-EKS-GREEN/1f876ef17471a73e
